const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_FAILED = "LOGIN_FAILED";
const CLEAR_ERRORS = "CLEAR_ERRORS";
const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
const LOAD_USER_FAILED = "LOAD_USER_FAILED";
const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAILED = "GET_USER_FAILED";
const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
const DELETE_USER_PROFILE_REQUEST = "DELETE_USER_PROFILE_REQUEST"
const DELETE_USER_PROFILE_SUCCESS = "DELETE_USER_PROFILE_SUCCESS";
const DELETE_USER_PROFILE_FAIL = "DELETE_USER_PROFILE_FAIL";
const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";
const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
const DELETE_USER_REQUEST = "DELETE_USER_REQUEST"
const DELETE_USER_FAIL = "DELETE_USER_FAIL"
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS"

export {
    LOGIN_REQUEST,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    CLEAR_ERRORS,
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCCESS,
    REGISTER_USER_FAILED,
    LOAD_USER_REQUEST,
    LOAD_USER_SUCCESS,
    LOAD_USER_FAILED,
    LOGOUT_USER_SUCCESS,
    LOGOUT_USER_FAILED,
    GET_USER_SUCCESS,
    GET_USER_FAILED,
    UPDATE_PROFILE_RESET,
    UPDATE_PROFILE_SUCCESS,
    UPDATE_PROFILE_FAIL,
    DELETE_USER_PROFILE_SUCCESS,
    DELETE_USER_PROFILE_FAIL,
    DELETE_USER_PROFILE_REQUEST,
    GET_ALL_USER_REQUEST,
    GET_ALL_USER_SUCCESS,
    GET_ALL_USER_FAIL,
    USER_DETAILS_SUCCESS,
    USER_DETAILS_REQUEST,
    USER_DETAILS_FAIL,
    UPDATE_USER_REQUEST,
    UPDATE_USER_FAIL,
    UPDATE_USER_SUCCESS,
    DELETE_USER_REQUEST,
    DELETE_USER_FAIL,
    DELETE_USER_SUCCESS
}